name: React build
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'ap-northeast-2'
    steps:
      - name: Checkout source code # 레포지토리 체크아웃
        uses: actions/checkout@master

      - name: Upload binary to s3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --exclude '*' --include 'index.html'
        env: 
          AWS_S3_BUCKET: ${{ secrets.BUCKET_NAME }}
            
      - name : Invalidate cashe CloudFront
        uses: chetan/invalidate-cloudfront-action@master
        env :
          DISTRIBUTION : ${{secrets.AWS_CLOUNDFRONT_ID}}
          PATHS :
            "/index.html"
          continue-on-error: true
